module.exports = [
	"Angel Aquas",
	"Beverly Reyes",
	"Bryan Pacana",
	"Bryan Tran",
	"Freddie Talai",
	"Garry Maghari",
	"German Pineda",
	"Hadi Burpee",
	"Jacob Adler",
	"Jobi Mathai",
	"Joseph Clarke",
	"Louis McGruder",
	"Lynn Thompson",
	"Margaret He",
	"Nicholas Antonyan",
	"Olga Vyrvich",
	"Oswaldo Medina",
	"Rajiv Jagirdar",
	"Rashid Green",
	"Vaibhav Pandey",
	"William Collins"
];